<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6Y250Qw\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6Y250Qw/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6Y250Qw.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6Y250Qw\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container6Y250Qw\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '6Y250Qw',
    'container.build_id' => 'b0b3f260',
    'container.build_time' => 1566568979,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6Y250Qw');
